#!/usr/bin/python3

import datetime
import hashlib
import shutil
import subprocess
import json, os, sys

import requests
import utils
import youtube as youtube_module
import notion as notion_module
import config
import bookmarks as bookmarks_module

#Does all the daily tasks

youtube = youtube_module.Youtube()
notion = notion_module.Notion()
bookmarks = bookmarks_module.Bookmarks()

def sortMusicPlaylists():

    print("Sorting music playlists...")

    ytPlaylists = {}

    for playlistId in config.ytMusicPlaylists:
        playlistInfo = youtube.get_playlist_info(playlistId)
        print("Sorting playlist '%s' (%s)" % (playlistId, playlistInfo["title"]))

        videos = youtube.get_playlist_videos(playlistId)

        songHashes = set()
        duplicatedSongHashes = set()
        for video in videos:
            if video["songHash"] in songHashes:
                duplicatedSongHashes.add(video["songHash"])
            else:
                songHashes.add(video["songHash"])

        for video in videos:
            if not video["isAvailable"]:
                if video["songHash"] in duplicatedSongHashes:
                    print("Video %s (%s) is no longer available but is a duplicate, removing it" % (video["id"], video["songHash"]))
                    youtube.delete_playlist_item(video["playlistitem_id"])
                    videos = [v for v in videos if v["id"] != video["id"]]
                elif video["title"] in ["Deleted video", "Privated video"]:
                    print("Video %s (%s) is no longer available, removing it" % (video["id"], video["songHash"]))
                    youtube.delete_playlist_item(video["playlistitem_id"])
                    videos = [v for v in videos if v["id"] != video["id"]]
                else:
                    if youtube.isAutoGeneratedVideo(video):
                        newId = youtube.get_new_video_id(video["id"])
                        if newId == video["id"]:
                            print("Video %s (%s) is no longer available and no new id was found, put it again in the playlist for it to be removed" % (video["id"], video["songHash"]))
                        else:
                            print("Video %s (%s) is no longer available, but is auto-generated, replacing it with %s" % (video["id"], video["songHash"], newId))
                            newVideo = youtube.add_video_to_playlist(playlistId, newId, video["position"])
                            youtube.delete_playlist_item(video["playlistitem_id"])
                            video["playlistitem_id"] = newVideo["playlistitem_id"]
                            video["id"] = newId
                            video["title"] = newVideo["title"]
                            video["description"] = newVideo["description"]
                            video["channelName"] = newVideo["channelName"]
                            video["channelId"] = newVideo["channelId"]
                            video["publishedAt"] = newVideo["publishedAt"]
                            video["songHash"] = youtube.getSongHash(newVideo)
                            video["isAvailable"] = newVideo["isAvailable"]

                    else:
                        print("Video %s (%s) is no longer available, put it again in the playlist for it to be removed" % (video["id"], video["songHash"]))


        uniqueVideos = {}
        for video in videos:
            videoHash = video["songHash"]
            if videoHash in uniqueVideos:
                print("Duplicate detected: video at pos %s with id %s '%s' is the same as video at pos %s with id %s '%s'" % (video["position"], video["id"], video["title"], uniqueVideos[videoHash]["position"], uniqueVideos[videoHash]["id"], uniqueVideos[videoHash]["title"]))
                #If the position is low, then it is a song I recently added and thus should be removed as there would be no meaningful difference (eg live/studio)
                if uniqueVideos[videoHash]["position"] < 20 and uniqueVideos[videoHash]["position"] < video["position"]:
                    print("Removing video %s" % (uniqueVideos[videoHash]["id"]))
                    youtube.delete_playlist_item(uniqueVideos[videoHash]["playlistitem_id"])
                    videos = [v for v in videos if v["id"] != uniqueVideos[videoHash]["id"]]
                elif video["position"] < 20 and video["position"] < uniqueVideos[videoHash]["position"]:
                    print("Removing video %s" % (video["id"]))
                    youtube.delete_playlist_item(video["playlistitem_id"])
                    videos = [v for v in videos if v["id"] != video["id"]]


            else:
                uniqueVideos[videoHash] = video


        artistCounts = {}
        for video in videos:
            artist = video["songHash"].split(" - ")[0]
            if artist in artistCounts:
                artistCounts[artist] += 1
            else:
                artistCounts[artist] = 1

        artistCounts = {k: v for k, v in sorted(artistCounts.items(), key=lambda item: -item[1])}
        #for artist, artistCount in artistCounts.items():
        #    print(artist, artistCount)

        if playlistId not in config.ytMusicPlaylistsToNotSort:
            videos = youtube.sort_playlist(playlistId, videos)

        #for video in videos:
        #    print(video["position"], self.getSongHash(video))

        ytPlaylists[playlistInfo["title"]] = {
            "id": playlistId,
            "videos":  [{
                "title": v["title"],
                #"description": v["description"],
                "channelName": v["channelName"],
                "channelId": v["channelId"],
                "id": v["id"],
                "publishedAt": v["publishedAt"],
                "songHash": v["songHash"],
            } for v in videos]
        }


    markdownResult = "<script setup>\nimport YtPlaylist from '../components/YtPlaylist.vue'\n</script>\n\n# Music playlists\n\nSee https://github.com/Zezombye/backup-scripts/blob/master/backup.py for my playlist sorting + backup script.\n\n"
    for playlistName, playlistData in ytPlaylists.items():
        markdownResult += "## ["+utils.sanitizeForMarkdown(playlistName)+"](https://youtube.com/playlist?list="+playlistData["id"]+")\n\n"
        markdownResult += "<YtPlaylist :videos=\""+utils.sanitizeForHtml(json.dumps(playlistData["videos"], indent=4, ensure_ascii=False))+"\"/>\n\n"

    with open("D:/repos/blog/articles/playlists.md", "w+", encoding="utf-8", newline="\n") as f:
        f.write(markdownResult)


def backupYtPlaylists():
    print("Backing up playlists...")
    for playlistId in config.ytPlaylistsToDownload:
        youtube.download_playlist(playlistId)

    for playlistId in config.ytMusicPlaylistsToDownload:
        youtube.download_playlist(playlistId, audioOnly=True)


def backupNotion():
    print("Backing up Notion...")
    notion.backupAllPages()

def backupBookmarks():
    print("Backing up bookmarks...")
    bookmarksList = bookmarks.getBookmarks()
    with open("D:/bkp/bookmarks.json", "w+", encoding="utf-8", newline="\n") as f:
        f.write(json.dumps(bookmarksList, indent=4, ensure_ascii=False))

    publicBookmarks = [b for b in bookmarksList if b["title"] != "Streaming"]

    with open("D:/repos/blog/articles/bookmarks.md", "w+", encoding="utf-8", newline="\n") as f:
        f.write("---\naside: false\n---\n\n# Useful websites\n\n" + bookmarks.bookmarksToMarkdown(publicBookmarks))


def publishAutoBackups():

    files = ["articles/bookmarks.md", "articles/playlists.md"]

    subprocess.check_output("git -C D:/repos/blog add " + " ".join(files), shell=True)
    status = subprocess.check_output("git -C D:/repos/blog status --porcelain", shell=True).decode().strip().splitlines()
    filesToCommit = []
    for file in files:
        if " M " + file in status or "M  " + file in status or "AM " + file in status:
            filesToCommit.append(file)

    if len(filesToCommit) == 0:
        print("Nothing to auto backup")
        return
    
    print("Publishing auto backup for " + ", ".join(filesToCommit))
    
    subprocess.check_output("git -C D:/repos/blog commit -m \"[Auto backup] " + ", ".join(filesToCommit) + "\" " + " ".join(filesToCommit), shell=True)
    subprocess.check_output("git -C D:/repos/blog push", shell=True)


if __name__ == "__main__":

    sortMusicPlaylists()
    #backupYtPlaylists()
    #backupNotion()
    backupBookmarks()
    publishAutoBackups()

    print("Done")
